### ISSUE TITLE
Sounder SIPS L0 Data in U-DS (January 2016)

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-data-services#2]
Upload Sounder SIPS L0 data for the period of January, 2016.

**Comment by wphyojpl** [comment]
### SNPP URLs

https://snppl0.gesdisc.eosdis.nasa.gov/data/SNPP_ATMS_Level0_T/ATMS_SCIENCE_Group/
https://snppl0.gesdisc.eosdis.nasa.gov/data/SNPP_Common_Level0_T/SNPP_EphAtt/
https://snppl0.gesdisc.eosdis.nasa.gov/data/JPSS1_ATMS_Level0_T/ATMS_SCIENCE_Group/
https://snppl0.gesdisc.eosdis.nasa.gov/data/JPSS1_Common_Level0_T/JS1_EphAtt/

**Comment by wphyojpl** [comment]
### How to downget SNPP L0 data using UDS-2 VPC

1. Create new security group where all 3 subnet of UDS-2 VPC can ssh to one another AND jpl IP addresses can SSH to one another
1. Update Network ACL Inbound Rules for public subnet of UDS-2 VPC to allow ssh from JPL IP addresses
1. Spin up an EC2 with public IP in public subnet so that it can be ssh from laptop (act as a bastion host). Since it has a public IP, it cannot access SNPP site. 
1. Spin up another EC2 without public IP in private subnet which can be ssh from bastion host
1. create a `.netrc` file with this line: `machine urs.earthdata.nasa.gov login <urs username> password <urs password>`
1. In urs.earthdata.nasa.gov profile, add `NASA GESDISC DATA ARCHIVE` to authorized apps.
1. Run this to list the files: `wget --load-cookies ~/.netrc --save-cookies ~/.netrc --keep-session-cookies -nH -nd 'https://snppl0.gesdisc.eosdis.nasa.gov/data/SNPP_ATMS_Level0_T/ATMS_SCIENCE_Group/' -O -  `
1. Add the folders as they are listed. Should be scripted to get all files. 
1. Run this to download 1 file: `wget --load-cookies ~/.netrc --save-cookies ~/.netrc --keep-session-cookies --content-disposition 'https://snppl0.gesdisc.eosdis.nasa.gov/data/SNPP_Common_Level0_T/SNPP_EphAtt/2011/344/P1570011AAAAAAAAAAAAXT11344140000000.PDS'`
1. Run this to download files recursively: `wget --load-cookies ~/.urs_cookies --save-cookies ~/.urs_cookies --keep-session-cookies -r -c -nH -nd -np -A nc4,xml  --content-disposition "https://snppl0.gesdisc.eosdis.nasa.gov/data/SNPP_Common_Level0_T/SNPP_EphAtt/2011/344/"`

**Comment by wphyojpl** [comment]
source code is pushed to : https://github.com/unity-sds/unity-data-services develop branch. 
Closing this.
