### ISSUE TITLE
[New Feature]: Update DAPA Endpoint name in api-gateway

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-data-services#203]
**Checked for duplicates**

Nope.

**Alternatives considered**

Yes, no satisfying alternative exists.

**Related problems**

No, but will make urls more memorable/easier for a user.

**Describe the feature request**

Currently, to access data/collections within a unity environment (dev, test), one needs to access the API Gateway and then interact with an `/am-uds-dapa` endpoint. This is fine for internal use, but since it gets exposed to the user for collection, granule, and processes calls, i'd like this to be a bit more generic. 

Can we update the builds and environments to create a `/data` endpoint? This would be a bit clearer and consistent across the environments. We'll need to work with @jjacob7734 from U-AS to get this working as it will impact him as well.

Ideally, we'd support both endpoints (/am-uds-dapa AND /data) and be able to monitor traffic as we switch them over. I'm curious if we should also add a version there? `/data/v1/collection...` to allow us to version the API if needed. I've included Ramesh here to discuss the versioning options and to make him aware.

**Comment by wphyojpl** [comment]
This is a change in terraform API gateway repo in U-CS (i think) plus [this variable](https://github.com/unity-sds/unity-data-services/blob/develop/tf-module/unity-cumulus/main.tf#L118) during deploy time.

**Comment by wphyojpl** [comment]
From UDS deployment terraform [uds_base_url](https://github.jpl.nasa.gov/unity-uds/cumulus-template-deploy/blob/develop/cumulus-tf/tfvars/mcp-dev.tfvars#L161) needs to be updated if it is not cloudfront URL but API gateway URL. 
[dapa_api_prefix](https://github.jpl.nasa.gov/unity-uds/cumulus-template-deploy/blob/develop/cumulus-tf/tfvars/mcp-dev.tfvars#L159) also needs to be updated. 
[unity-rest-api-gateway-oas30.yaml](https://github.jpl.nasa.gov/unity-uds/cumulus-template-deploy/blob/develop/cumulus-tf/tfvars/mcp-dev.tfvars#L159) also needs to be updated, but this is a deprecated location. I'm not sure the new location. 

I think only those 3 places needs to be updated for a different prefix like `/data`.

**Comment by ramesh-maddegoda** [comment]
@wphyojpl and @ngachung , Instead of centrally managing  [unity-rest-api-gateway-oas30.yaml](https://github.jpl.nasa.gov/unity-uds/cumulus-template-deploy/blob/develop/cumulus-tf/tfvars/mcp-dev.tfvars#L159), now we update API gateway paths using terraform. These terraform scripts does not have to be in a single centralized terraform script. Anyone who has access to update the API Gateway can execute the terraform script to add/update paths in API Gateway.

The following code example shows the way to update an existing API Gateway with Terraform.
https://github.com/unity-sds/unity-cs-infra/blob/main/terraform-shared-services-api-gateway-updater_module/main.tf

cc: @galenatjpl
